### ISSUE TITLE
Simplify init.d/buildkite-agent with --spawn flag

### ISSUE THREAD

**Issue by drnic** [talon-one/gce-buildkite-alpine#8]
https://github.com/talon-one/gce-buildkite-alpine/blob/master/etc/init.d/buildkite-agent#L60-L72

There is `buildkite-agent start --spawn 5` flag now https://github.com/buildkite/agent/blob/be3099db4e08ecb813bbe4d8ea238b60b79fd430/CHANGELOG.md#added-8 -- might help simplify this init.d script?

**Comment by Eun** [comment]
Might be a good idea, however I think having seperate build, plugins and hooks folder per agent is valuable on troubleshooting
